---
# tasks file for supervisor
- name: Install yum requirments
  yum: name={{ item }} state=latest
  with_items: ["python-devel", "openldap-devel", "python-setuptools", "supervisor", "lzo-devel"]

- name: Install dev tools
  yum:
    name: "@development tools"
    state: latest

- name: Create log directory
  file: path=/var/log/supervisord state=directory

- name: Create Galaxy user
  user:
    name: galaxy
    password: a3b5e89c680a19af9938e385b5f2e52e3c9f5f502c6a5cdcecbfde68d964118fa63861684a07237544c4054f147826d705666269ab679164f8fe92bd1ab26a91

- name: Add supervisord config
  copy:
    src: supervisord.conf
    dest: /etc/supervisord.conf
  notify:
    - Start supervisord
