---
# tasks file for postgres
- import_tasks: install_pip.yml

- name: Install Postgres with Yum
  yum:
    name: '{{ item }}'
    state: latest
  with_items: ["postgresql-server", "postgresql-contrib"]

- name: Create a new PostgreSQL database cluster
  command: postgresql-setup initdb

- name: Copy in the pg_hba.conf for access control
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: galaxy
    group: galaxy 

- name: manually start postgresql handler
  command: systemctl start postgresql

- name: enable on boot
  command: systemctl enable postgresql

- name: Create db user
  user:
    name: "{{ domain }}"
    password: a3b5e89c680a19af9938e385b5f2e52e3c9f5f502c6a5cdcecbfde68d964118fa63861684a07237544c4054f147826d705666269ab679164f8fe92bd1ab26a91

- name: install requirments for ansible posgresql module on host
  pip:
    name: psycopg2
    state: latest

- name: Decrypt DB secrets
  include_vars: secrets.yml

- name: Create the "{{ domain }}" user
  postgresql_user:
    name: "{{ domain }}"
    password: "{{ db_password }}"
    encrypted: True
  become_user: postgres
  notify: restart postgresql

- name: create postgresql database
  postgresql_db:
    name: "{{ domain }}"
    owner: "{{ domain }}"
  become_user: postgres    
  notify: restart postgresql
    

